build(demo): set GitHub branch to V4.x
FlowingCode/OrgChartAddon pull request #75
Opened 2023-07-21 13:28 UTC by paodb

2023-07-21 17:00 UTC, javier-godoy requested changes
Commit must be based on 4.x branch

2023-07-22 15:54 UTC, javier-godoy approved these changes

2023-07-22 15:55 UTC, javier-godoy commented on src/test/java/com/flowingcode/vaadin/addons/orgchart/OrgchartDemoView.java
> +@GithubBranch("4.x")
Branch is `v4x`, not `4.x`

2023-07-22 15:55 UTC, javier-godoy requested changes
Branch is

2023-07-23 14:18 UTC, paodb commented on src/test/java/com/flowingcode/vaadin/addons/orgchart/OrgchartDemoView.java
> +@GithubBranch("4.x")
Fixed

2023-07-24 04:17 UTC, javier-godoy approved these changes

2023-07-24 04:17 UTC, merged